name: package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up
        run: |
          docker --version
          docker-compose --version
          docker-compose pull --parallel
          echo "${GITHUB_REF}"
      - name: Build docker image
        run: |
          make build
      - name: Start services
        run: |
          make services
      - name: Run tests
        run: make test
      # - name: Push docker image (hash)
      #   run: |
      #     docker tag alephdata/ingest-file alephdata/ingest-file:${GITHUB_SHA}
      #     docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
      #     docker push alephdata/ingest-file:${GITHUB_SHA}
      # - name: Push docker images for tags
      #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      #   run: |
      #     export ALEPH_TAG=${GITHUB_REF/refs\/tags\//}
      #     docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
      #     docker pull alephdata/aleph-ui-production:${GITHUB_SHA}
      #     for IMAGE in aleph aleph-ui-production ingest-file; do
      #       docker tag alephdata/${IMAGE}:${GITHUB_SHA} alephdata/${IMAGE}:${ALEPH_TAG};
      #       docker push alephdata/${IMAGE}:${ALEPH_TAG};
      #       docker tag alephdata/${IMAGE}:${GITHUB_SHA} alephdata/${IMAGE}:latest;
      #       docker push alephdata/${IMAGE}:latest;
      #     done;
