name: package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up
        run: |
          docker --version
          docker-compose --version
          echo "${GITHUB_REF}"
          docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
          docker-compose pull -q redis postgres convert-document
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: Build docker image
        run: |
          make build
      - name: Start services
        run: |
          make services
      - name: Run tests
        run: make test
      - name: Push docker image (hash)
        run: |
          docker tag alephdata/ingest-file:latest alephdata/ingest-file:${GITHUB_SHA}
          docker push alephdata/ingest-file:${GITHUB_SHA}
      - name: Push docker images for tags
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          export TAG=${GITHUB_REF/refs\/tags\//}
          docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
          docker tag alephdata/ingest-file:latest alephdata/ingest-file:${TAG};
          docker push alephdata/ingest-file:${TAG};
          docker push alephdata/ingest-file:latest;
