name: package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up
        run: |
          docker --version
          docker-compose --version
          echo "${GITHUB_REF}"

          docker-compose pull -q redis postgres convert-document
          docker pull -q ghcr.io/alephdata/ingest-file:cache
      - name: Start services
        run: |
          make services
      - name: Build docker image
        run: |
          make build
      - name: Run tests
        run: make test
      - name: Push docker image (hash)
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker tag ghcr.io/alephdata/ingest-file ghcr.io/alephdata/ingest-file:${GITHUB_SHA}
          docker push ghcr.io/alephdata/ingest-file:${GITHUB_SHA}
          docker tag ghcr.io/alephdata/ingest-file ghcr.io/alephdata/ingest-file:cache
          docker push ghcr.io/alephdata/ingest-file:cache
      - name: Push docker images for tags
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          export TAG=${GITHUB_REF/refs\/tags\//}
          docker tag ghcr.io/alephdata/ingest-file ghcr.io/alephdata/ingest-file:${TAG};
          docker push ghcr.io/alephdata/ingest-file:${TAG};
          docker push ghcr.io/alephdata/ingest-file;
